using System;
using System.Diagnostics;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using System.Threading.Tasks;
using nifly;
using System.Threading;

namespace FaceGenChecker
{
    public class Program
    {
        static Lazy<Settings.Settings> _settings = null!;
        static internal Settings.Settings settings => _settings.Value;

        private static IPatcherState<ISkyrimMod, ISkyrimModGetter>? _state;
        public static IPatcherState<ISkyrimMod, ISkyrimModGetter> PatcherState
        {
            get => _state!;
        }
        private static MergeInfo? _mergeInfo;
        public static Task<int> Main(string[] args)
        {
            return SynthesisPipeline.Instance.SetTypicalOpen(GameRelease.SkyrimSE, "FaceGenChecker.esp")
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
                .Run(args);
        }

        public static readonly nifly.NifSaveOptions saveOptions = new nifly.NifSaveOptions()
        {
            optimize = false,
            sortBlocks = false
        };

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            Stopwatch stopWatch = new Stopwatch();
            stopWatch.Start();

            _state = state;
            if  (settings.control.FixMergedEditorID)
            {
                _mergeInfo = new MergeInfo(settings.paths.ConflictWinnerLocation);
            }

            // Analyze records in scope for models and textures
            MeshHandler meshHandler = new MeshHandler(settings, state);
            meshHandler.Analyze();
            long analysisTime = stopWatch.ElapsedMilliseconds;

            // validate each winning NPC record versus its winning mesh

            // Transform meshes, including any records with alternate textures
            meshHandler.ProcessMeshes();
            long meshTime = stopWatch.ElapsedMilliseconds - analysisTime;

            settings.diagnostics.logger.WriteLine("NPC analysis: {0} ms", analysisTime);
            settings.diagnostics.logger.WriteLine("Mesh processing: {0} ms", meshTime);
            settings.diagnostics.logger.Dispose();
        }
    }
}
